import { Person, Question } from './model';

export const categories: string[] = [
  'Teamwork',
  'Training and Learning Opportunities',
  'Meaningful Work',
  'Quality of Products and Services',
  'Accountability and Responsibility',
  'Decision-Making',
  'Management',
  'Work-Life Balance',
  'Compensation and Benefits',
  'Transparency',
  'Autonomy',
  'Hiring and Recruiting',
  'Values and Culture',
  'Tools and Infrastructure',
  'Career Growth Opportunities',
  'Recognition and Appreciation',
  'Remote Sites',
  'Cross-Team Collaboration',
  'Innovation',
  'Documentation',
  'Perks',
  'Communication',
  'Senior Leadership',
  'Physical Workspace',
  'Company Vision',
  'Process and Organizational Effectiveness',
  'Diversity',
  'Company Brand',
  'Customer Focus',
  'Meetings',
  'Sales',
  'Commute',
];

export const persons: Person[] = [
  {
    name: { firstName: 'Sara', lastName: 'Pargair Cohan' },
  },
  {
    name: { firstName: 'Ruchita', lastName: 'Joshi' },
  },
  {
    name: { firstName: 'Ayaz', lastName: 'Kadam' },
  },
  {
    name: { firstName: 'Anas', lastName: 'AI-Raheem' },
  },
  {
    name: { firstName: 'Di', lastName: 'Zhou' },
  },
];

export const questions: Question[] = [
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
];
