import { Person, Question } from './model';

export const categories: string[] = [
  'Teamwork',
  'Training and Learning Opportunities',
  'Meaningful Work',
  'Quality of Products and Services',
  'Accountability and Responsibility',
  'Decision-Making',
  'Management',
  'Work-Life Balance',
  'Compensation and Benefits',
  'Transparency',
  'Autonomy',
  'Hiring and Recruiting',
  'Values and Culture',
  'Tools and Infrastructure',
  'Career Growth Opportunities',
  'Recognition and Appreciation',
  'Remote Sites',
  'Cross-Team Collaboration',
  'Innovation',
  'Documentation',
  'Perks',
  'Communication',
  'Senior Leadership',
  'Physical Workspace',
  'Company Vision',
  'Process and Organizational Effectiveness',
  'Diversity',
  'Company Brand',
  'Customer Focus',
  'Meetings',
  'Sales',
  'Commute',
];

export const persons: Person[] = [
  {
    name: { firstName: 'Sara', lastName: 'PCohan' },
    score: 80,
    emotionDistribution: [
      { emotionName: 'confident', percentile: 0.4 },
      { emotionName: 'optimistic', percentile: 0.4 },
      { emotionName: 'playful', percentile: 0.4 },
    ],
  },
  {
    name: { firstName: 'Ruchita', lastName: 'Joshi' },
    score: 74,
    emotionDistribution: [
      { emotionName: 'confident', percentile: 0.4 },
      { emotionName: 'optimistic', percentile: 0.4 },
      { emotionName: 'playful', percentile: 0.4 },
    ],
  },
  {
    name: { firstName: 'Ayaz', lastName: 'Kadam' },
    score: 56,
    emotionDistribution: [
      { emotionName: 'confident', percentile: 0.4 },
      { emotionName: 'optimistic', percentile: 0.4 },
      { emotionName: 'playful', percentile: 0.4 },
    ],
  },
  {
    name: { firstName: 'Anas', lastName: 'AI-Raheem' },
    score: 47,
    emotionDistribution: [
      { emotionName: 'confident', percentile: 0.4 },
      { emotionName: 'optimistic', percentile: 0.4 },
      { emotionName: 'playful', percentile: 0.4 },
    ],
  },
  {
    name: { firstName: 'Di', lastName: 'Zhou' },
    score: 30,
    emotionDistribution: [
      { emotionName: 'confident', percentile: 0.4 },
      { emotionName: 'optimistic', percentile: 0.4 },
      { emotionName: 'playful', percentile: 0.4 },
    ],
  },
];

export const questions: Question[] = [
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '1',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'how old are you',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
  {
    id: '2',
    answer: 'asdf',
    emotion_id: '1',
    attributes_id: '1',
    question: 'hows the weather today',
    score: 98,
    user_id: '123',
    weights_id: '123',
  },
];

// angry: 0,
//      annoyed: 0,
//      appreciative: 0.6108686747216702,
//      confident: 0.47754420534208447,
//      confused: 0,
//      excited: 0.47754420534208447,
//      happy: 0.5398856938274154,
//      optimistic: 0.47754420534208447,
//      playful: 0,
//      sad: 0.08119807934607087,
//      satisfied: 0.6862401627571847,
//      stressed: 0.05955908087184198,
//      thoughtful: 0.08569037852704633,
//      upset: 0.20693528211727594,
//      worried: 0.026295335999970082
